site: "Ryan Shea"
url: https://ryanshea.info
title: "Ryan Shea"
description: "Writer. Stories, poems, and audio work. Co-editor of Cover."
twitter:
  username: ryanjshea
  card: summary_large_image
  creator: ryanjshea
author:
  twitter: ryanjshea
  name: Ryan Shea
  avatar: /favicon.png
  email: arr.shea@gmail.com
  url: https://ryanshea.info
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

# Performance optimizations
incremental: true
future: true
unpublished: false

# Feed settings
feed:
  excerpts: true
  path: atom.xml

# SEO settings
seo:
  type: Person
  name: Ryan Shea
  same_as:
    - https://www.threads.com/@ryanjshea
    - https://bsky.app/profile/rshea.bsky.social

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
